### ISSUE TITLE
Unhandled error event on quit

### ISSUE THREAD

**Issue by dhax** [jeffijoe/icebug#4]
running 'npm run debug' with debug script being something like: 'icebug src/bin/server.js' and then quitting the process with CTRL^C I get the following error:

```
events.js:154
      throw er; // Unhandled 'error' event

Error: read EIO
    at exports._errnoException (util.js:890:11)
    at TTY.onread (net.js:550:26)
```

Strangely, running from node_modules folder (./node_modules/icebug/bin/icebug.js src/bin/server.js) there is no error, but needs two CTRL^C hits to quit the process.

I couldn't figure out what is emitting the error, tried catching nodemon and child_process.fork errors but with no effect. 

OS X 10.11
node 5.8.0
npm 3.8.2

**Comment by jeffijoe** [comment]
When running from node_modules, you're using `node icebug.js`?

**Comment by dhax** [comment]
nodemon ./node_modules/icebug/bin/icebug.js src/bin/server.js
-> quits with single CTRL^C
node ./node_modules/icebug/bin/icebug.js src/bin/server.js
-> quits with double CTRL^C
./node_modules/icebug/bin/icebug.js src/bin/server.js
-> quits with double CTRL^C

Error could be related to node-inspector emitting an error when the socket connection is closed. 

```
events.js:154
      throw er; // Unhandled 'error' event

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:274:12)
    at Client.send (_debug_agent.js:168:15)
    at _debug_agent.js:56:14
    at Array.forEach (native)
    at DebugAPI.Agent.binding.onmessage (_debug_agent.js:55:18)
```

**Comment by jeffijoe** [comment]
That's odd - I'll have to look at how nodemon spawns.

**Comment by jeffijoe** [comment]
This looks interesting..

https://www.exratione.com/2013/05/die-child-process-die/

``` js
// A helper function to shut down the child.
child.shutdown = function () {
  // Get rid of the exit listener since this is a planned exit.
  this.removeListener("exit", this.onUnexpectedExit);
  this.kill("SIGTERM");
}

// SIGTERM AND SIGINT will trigger the exit event.
process.once("SIGTERM", function () {
  process.exit(0);
});
process.once("SIGINT", function () {
  process.exit(0);
});
// And the exit event shuts down the child.
process.once("exit", function () {
  child.shutdown();
});

// This is a somewhat ugly approach, but it has the advantage of working
// in conjunction with most of what third parties might choose to do with
// uncaughtException listeners, while preserving whatever the exception is.
process.once("uncaughtException", function (error) {
  // If this was the last of the listeners, then shut down the child and rethrow.
  // Our assumption here is that any other code listening for an uncaught
  // exception is going to do the sensible thing and call process.exit().
  if (process.listeners("uncaughtException").length === 0) {
    child.shutdown();
    throw error;
  }
});
```

@DiknT if you have the time, in your local install of icebug, add the above code after https://github.com/jeffijoe/icebug/blob/master/lib/icebug.js#L57 - rename `child` in the snippet above to `inspectorRunning` (ChildProcess from fork) and try it out, see if it solves the issue on your end? Don't want to add this and publish if it won't work.

**Comment by dhax** [comment]
I tried this and it 'swallows' the error but uncaughtException shouldn't be used and also might be deprecated. But what I don't understand (other than why there's no problem on windows) is why this error only pops up when icebug is started by 'npm run' and not when invoked from modules folder with './node_modules/icebug/bin/icebug.js src/bin/server.js'

**Comment by jeffijoe** [comment]
That's odd indeed. I'd investigate further if I had a Mac, but sadly I don't. If you somehow get it working I'll gladly accept a PR. :)
